plugins {
    id 'org.jetbrains.kotlin.jvm' version '1.7.20'
    id 'maven-publish'
    id "pl.allegro.tech.build.axion-release" version "1.12.1"
    id "org.jetbrains.dokka" version "1.7.20"
}

repositories {
   mavenCentral()
}

tasks.dokkaHtml.configure {
    outputDirectory.set(file("$buildDir/javadoc"))
}

sourceSets {
    noop {
        java.srcDir 'src/noop/kotlin'
    }
}

dependencies {
    implementation platform('org.jetbrains.kotlin:kotlin-bom')
    implementation 'org.jetbrains.kotlin:kotlin-stdlib-jdk8'

    implementation 'org.slf4j:slf4j-api:2.0.3'
    testImplementation 'org.slf4j:slf4j-simple:2.0.3'
    testImplementation 'org.jetbrains.kotlin:kotlin-test-junit5'

    noopImplementation 'org.slf4j:slf4j-nop:2.0.3'
    noopImplementation 'org.jetbrains.kotlin:kotlin-stdlib-jdk8'
}

task dokkaJar(type: Jar) {
    group = JavaBasePlugin.DOCUMENTATION_GROUP
    description = "Assembles KDocs with Dokka"
    archiveClassifier.set("javadoc")
    from(tasks.dokkaHtml)
    dependsOn(tasks.dokkaHtml)
}

task sourcesJar(type: Jar) {
    archiveClassifier.set("sources")
    from(sourceSets.getByName("main").allSource)
}

task noopSources(type: Jar) {
    archiveClassifier.set("sources")
    from(sourceSets.noop.allSource)
}

task noopBinary(type: Jar) {
    archiveClassifier.set("")
    from(sourceSets.noop.output)
}

publishing {
    publications {
        noop(MavenPublication) {
            artifact noopSources
            artifact noopBinary

            pom {
                name = "ktee-noop"
                artifactId = "notee"
            }
        }

        mavenJava(MavenPublication) {
            from components.java
            artifact sourcesJar
            artifact dokkaJar

            pom {
                name = "ktee"
                artifactId = "yetee"

                description = "KTee is Tee for Kotlin code pipelines. " +
                        "If you love the unix command line tee, you know what we mean."
                url.set("https://github.com/medly/ktee")
                licenses {
                    license {
                        name = "MIT"
                        url = "https://opensource.org/licenses/MIT"
                    }
                }

                developers {
                    developer {
                        id = "kdabir"
                        name = "Kunal Dabir"
                        email = "kd@medly.com"
                    }
                }

                scm {
                    connection = "scm:git:git@github.com:medly/ktee.git"
                    developerConnection = "scm:git:ssh://github.com/medly/ktee.git"
                    url = "https://github.com/medly/ktee"
                }
            }
        }
    }
}

scmVersion {
    tag {
        prefix = 'v'
        versionSeparator = ''
    }

    localOnly = true
}

group = "com.medly"
project.version = scmVersion.version